version: '1.0'

services:
  db:
    image: postgres:16.0-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PW}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432