version: '1.0'

services:
  db:
    image: postgres:16.0-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: tweets-api-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_PW: ${DB_PW}
    links:
      - "db"
    ports:
      - 3000:3000